#!/bin/ash

# default to use shutdown command
ACTION="poweroff"

# Get shutdown parameters
# How Qemu-GA invokes -h -P +0 by default
while [ -n "$1" ]; do
case "$1" in
         -r)
         ACTION="reboot"
shift
         ;;

         -k)
         ACTION="warning"
shift
         ;;

         -h|-H)
         ACTION="halt"
shift
         ;;

         -n)
         ACTION="poweroff"
shift
         ;;

         -c)
         echo "Cancel shutdown, but not support the Openwrt!" > /dev/kmsg
         ACTION="stop"
shift
         ;;

         -p|-P)
         ACTION="poweroff"
shift
         ;;

         -*)
shift
;;

*)
break
;;

esac
done

if [ $# == 0 ]; then
     echo "Shutting down without any params" > /dev/kmsg
     /sbin/poweroff

elif [ "$ACTION" = "poweroff" ]; then
     /sbin/poweroff;

elif [ "$ACTION" = "reboot" ]; then
     /sbin/reboot

elif [ "$ACTION" = "warning" ]; then
     echo "shutdown warning">/dev/kmsg
     /sbin/poweroff;

elif [ "$ACTION" = "halt" ]; then
     /sbin/halt
fi
