#!/bin/ash
# shellcheck shell=dash
#################################################################
# Copyright (c) 2022 By Eliminater74                            #
#                                                               #
# This is free software, licensed under the MIT License.        #
# See /LICENSE for more information.                            #
#                                                               #
#                                                               #
# Updated By Eliminater74 07/29/2022                            #
#################################################################

sleep 30 ### <-- Needed to wait till internet is up before trying

FIRSTBOOT=/root/FIRST_BOOT

if [ ! -f "$FIRSTBOOT" ]; then
    # Run autoSQM to setup Upload/Download
    /usr/lib/OpenWrtScripts/autoSQM.sh
    touch $FIRSTBOOT

    echo "FirstBoot DONE!"
    logger -t FirstBoot -p info "Running FirstBoot Script Finished"
fi

exit 0