#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-only
#
# Copyright (C) 2021 ImmortalWrt.org
#
# Copyright (C) 2022 PureFusionWRT (Not Original Author)

set -x

#STAGING_DIR_HOST="$(make --no-print-directory -C target/linux val.STAGING_DIR_HOST)"

export TOPDIR="$PWD"
export STAGING_DIR_HOST="$(make --no-print-directory -C target/linux val.STAGING_DIR_HOST)"
export MKHASH="$STAGING_DIR_HOST/bin/mkhash"
export PATH="$STAGING_DIR_HOST/bin":"$PATH"

BIN_DIR="$(make --no-print-directory -C target/linux val.BIN_DIR)"
PACKAGE_DIR="$(make --no-print-directory -C target/linux val.PACKAGE_DIR)"
KEY_BUILD="$(make --no-print-directory -C target/linux val.BUILD_KEY)"
KMOD_DIR="$(make --no-print-directory -C target/linux val.LINUX_VERSION val.LINUX_RELEASE val.LINUX_VERMAGIC | tr '\n' '-' | head -c -1)"

echo "$PACKAGE_DIR"
pushd "$BIN_DIR" || exit
rm -rf "kmods/$KMOD_DIR"
mkdir -p "kmods/$KMOD_DIR"

cp -fpR "packages"/automount* "kmods/$KMOD_DIR"/
for i in "packages"/kmod-*; do cp -fpR "$i" "kmods/$KMOD_DIR"/; done
popd

pushd "$BIN_DIR/kmods/$KMOD_DIR" || exit
"$TOPDIR"/scripts/ipkg-make-index.sh . 2>&1 > "Packages.manifest"
grep -vE "^(Maintainer|LicenseFiles|Source|SourceName|Require|SourceDateEpoch)" "Packages.manifest" > "Packages"
case "$(((64 + "$(stat -L -c%s "Packages")") % 128))" in
	110|111)
		echo -e "\033[33mWARNING: Applying padding in Packages to workaround usign SHA-512 bug!\033[0m"
		{ echo ""; echo ""; } >> "Packages"
	;;
esac
gzip -9nc "Packages" > "Packages.gz"
"$STAGING_DIR_HOST"/bin/usign -S -m "Packages" -s "$KEY_BUILD"
popd
