name: Cleaning

on:
  workflow_dispatch:
  schedule:
    - cron: 1 8 * * 1
  # watch:
  #   types: started

jobs:

  Cleanup-Old-Releases:
    runs-on: ubuntu-20.04
    steps:
      - name: Delete Older Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Cleanup-Old-Artifacts:
    runs-on: ubuntu-20.04
    steps:
      - name: Cleanup Old Action Artifacts
        uses: kolpav/purge-artifacts-action@master
        with:
          token: ${{ github.token }}
          expire-in: 5d

  Remove-Old-Artifacts:
    runs-on: ubuntu-20.04
    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          age: '1 day'
          skip-recent: 5

  Cleanup-Workflow-Logs:
    runs-on: ubuntu-20.04
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 6

  Delete-Workflow-Runs:
    runs-on: ubuntu-20.04
    steps:
      - name: Delete workflow runs
        uses: dmvict/clean-workflow-runs@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          run_conclusions: |
                  failure
                  timed_out
          save_period: 5
          save_min_runs_number: 1
          dry: false
