name: Quick Clean

on:
  workflow_dispatch:
  # schedule:
  #  - cron: 1 8 * * 1
  # watch:
  #   types: started

jobs:

  Cleanup-Old-Releases:
    runs-on: ubuntu-20.04
    steps:
      - name: Delete Older Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 1
          delete_tags: true
          env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Cleanup-Old-Artifacts:
    runs-on: ubuntu-20.04
    steps:
      - name: Cleanup Old Action Artifacts
        uses: kolpav/purge-artifacts-action@master
        with:
          token: ${{ github.token }}
          expire-in: 0

  Cleanup-Workflow-Logs:
    runs-on: ubuntu-20.04
    steps:
      - name: Cleanup Workflow Logs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1

  Clean-up-previous-workflow-runs:
    runs-on: ubuntu-20.04
    steps:
      - name: Delete previous workflow runs
        uses: egmacke/action-cleanup-workflow-runs@master
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          workflow: ${{ github.workflow }}
          retain: 2
          branch: ${{ github.branch }}
